package jira;

import jira.manager.*;
import jira.model.*;

import java.awt.*;

public class JiraDashboard {

    public static TaskJson generateJson(){

        TaskJson json = new TaskJson();
        json.setHeading("My heading");
        json.setMetaData(new List());

        return json;
    }


    // our UI

    public  static void main(String[] args){

        UniqueIdGenerator generator = new UniqueIdGenerator();

        DashboardMananger mananger = new DashBoardManagerImpl(generator);

        User u1 = mananger.createUser("Anshay");
        User u2 = mananger.createUser("Sasuke");
        User u3 = mananger.createUser("naruto");
        User u4 = mananger.createUser("luffy");
        User u5 = mananger.createUser("zoro");
        User u6 = mananger.createUser("rias");
        User u7 = mananger.createUser("joy boy");


        Task task = new Task();
        Task dummyTask = mananger.createTask(u1, task); // lets say unique ID is generated by User
        task.setTaskId(dummyTask.getTaskId());

        u1.addCcreatedTask(task);
        task.setCreatedUser(u1);
        // clicked new task
        task.setParent(null);
        task.setStatus(Status.TODO);


        // UI creates a new Task Description
        TaskJson json = generateJson();

        TaskDescription description = new TaskDescriptionImpl();

        description.setResultFromUI(json);
        task.setDescription(description);


        UserSearchEngine searchEngine = new UserSearchEngineImpl();
        searchEngine.pushedFromResults(u2); // set user U2 as the assignee user after owner search for him in dashboard
        User assignee = searchEngine.getUserResult();


        mananger.assignTask(task, assignee);
        task.setAssignedUser(assignee);


        // save all data to local DB as well.




    }
}
